name: Test & Build
on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependancies
        run: make install

      - name: Run Python test suite
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          make test


  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node 10
        uses: actions/setup-node@v1

      - uses: borales/actions-yarn@v2.0.0

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependancies
        run: make install

      - name: Build docs and deploy
        run: |
          git config --global user.name "${{ secrets.GH_NAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          echo "machine github.com login ${{ secrets.GH_NAME }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          cd website && yarn
          yarn deploy
        env:
          GIT_USER: ${{ secrets.GH_NAME }}
